/**
 * Simplified test runner that doesn't require full Next.js runtime
 *
 * Run with: npm run test:simple
 */

import { PrismaClient } from "@/lib/generated/prisma";



const prisma = new PrismaClient();

// Test helper
function assert(condition: boolean, message: string) {
  if (!condition) {
    console.error(`❌ FAILED: ${message}`);
    process.exit(1);
  }
  console.log(`✅ PASSED: ${message}`);
}

async function testDatabase() {
  console.log("========================================");
  console.log("Testing Database Schema");
  console.log("========================================\n");

  try {
    // Test 1: Database connection
    console.log("Test 1: Database connection");
    await prisma.$connect();
    assert(true, "Database connected successfully");
    console.log();

    // Test 2: User table exists
    console.log("Test 2: User table exists");
    const userCount = await prisma.user.count();
    assert(userCount >= 0, `User table accessible (${userCount} users)`);
    console.log();

    // Test 3: Project table exists
    console.log("Test 3: Project table exists");
    const projectCount = await prisma.project.count();
    assert(projectCount >= 0, `Project table accessible (${projectCount} projects)`);
    console.log();

    // Test 4: ProjectAsset table exists
    console.log("Test 4: ProjectAsset table exists");
    const assetCount = await prisma.projectAsset.count();
    assert(assetCount >= 0, `ProjectAsset table accessible (${assetCount} assets)`);
    console.log();

    // Test 5: Create test user (if not exists)
    console.log("Test 5: Create or find test user");
    let testUser = await prisma.user.findUnique({
      where: { email: "test@example.com" }
    });

    if (!testUser) {
      testUser = await prisma.user.create({
        data: {
          email: "test@example.com",
          username: "testuser",
          passwordHash: "test_password_hash", // 测试用的占位符哈希值
        }
      });
      console.log(`   Created test user: ${testUser.email}`);
    } else {
      console.log(`   Found existing test user: ${testUser.email}`);
    }
    assert(testUser !== null, "Test user exists");
    console.log();

    // Test 6: Create test project
    console.log("Test 6: Create test project");
    const testProject = await prisma.project.create({
      data: {
        name: `Test Project - ${new Date().toISOString()}`,
        userId: testUser.id,
        metadata: { test: true }
      }
    });
    assert(testProject !== null, `Project created with ID: ${testProject.id}`);
    console.log();

    // Test 7: Create test asset
    console.log("Test 7: Create test asset");
    const testAsset = await prisma.projectAsset.create({
      data: {
        name: "test-document.pdf",
        tosObjectKey: `projects/${testUser.id}/test-${Date.now()}.pdf`,
        projectId: testProject.id,
        metadata: {
          fileType: "pdf",
          fileSize: 102400,
          textContent: "This is a test document with sample content for knowledge base generation.",
          pageCount: 1,
          extractedAt: new Date().toISOString(),
        }
      }
    });
    assert(testAsset !== null, `Asset created with ID: ${testAsset.id}`);
    console.log();

    // Test 8: Fetch project with assets
    console.log("Test 8: Fetch project with assets");
    const projectWithAssets = await prisma.project.findUnique({
      where: { id: testProject.id },
      include: { assets: true }
    });
    assert(projectWithAssets !== null, "Project fetched successfully");
    assert(projectWithAssets!.assets.length === 1, `Project has ${projectWithAssets!.assets.length} asset(s)`);
    console.log();

    // Test 9: Update project metadata (simulate KB generation)
    console.log("Test 9: Update project metadata");
    const updatedProject = await prisma.project.update({
      where: { id: testProject.id },
      data: {
        metadata: {
          summary: "This is a test project summary generated by AI",
          keyPoints: ["Point 1", "Point 2", "Point 3"],
          categories: ["Test", "Development"],
          generatedAt: new Date().toISOString(),
          documentCount: 1,
          totalTextLength: 75,
        }
      }
    });
    const metadata = updatedProject.metadata as Record<string, unknown>;
    assert(metadata.summary !== undefined, "Project metadata updated with AI summary");
    const summary = metadata.summary;
    console.log(`   Summary: ${typeof summary === 'string' ? summary : String(summary)}`);
    console.log();

    // Test 10: Delete asset (cascading)
    console.log("Test 10: Delete asset");
    await prisma.projectAsset.delete({
      where: { id: testAsset.id }
    });
    const assetExists = await prisma.projectAsset.findUnique({
      where: { id: testAsset.id }
    });
    assert(assetExists === null, "Asset deleted successfully");
    console.log();

    // Test 11: Delete project (should cascade delete assets)
    console.log("Test 11: Delete project");
    await prisma.project.delete({
      where: { id: testProject.id }
    });
    const projectExists = await prisma.project.findUnique({
      where: { id: testProject.id }
    });
    assert(projectExists === null, "Project deleted successfully");
    console.log();

    console.log("========================================");
    console.log("✅ All database tests passed!");
    console.log("========================================");

  } catch (error) {
    console.error("\n========================================");
    console.error("❌ Test failed");
    console.error("========================================");
    console.error(error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

// Run tests
testDatabase();
